bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books,only:[:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites,only:[:create,:destroy]
    resources :post_comments,only:[:create,:destroy]
  end

  resources :users,only:[:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search', to: 'search#search'
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def self.search_for(content, method)
    if method == 'pefect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%' + content)
    else
      Book.where('title LIKE ?', '%' + content + '%')
    end
  end
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

bookers2/app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  attachment :profile_image

  validates :name,uniqueness: true,length: {in: 2..20}
  validates :introduction,length: {maximum: 50}

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  # フォロー機能ここから
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  # フォロー機能

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!,except: [:top,:about]

before_action :configure_permitted_parameters,if: :devise_controller?

def after_sign_in_path_for(resource)
  user_path(current_user)
end

protected

def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
end


end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :book_all

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
   if @new_book.save
    redirect_to book_path(@new_book[:id]), notice: 'You have created book successfully.'
   else
    @user = current_user
    render :index
   end
  end

  def index
    @new_book = Book.new
    @user = current_user
    # @books = Book.all   before_actionで定義済み
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    # @books = Book.all  before_actionで定義済み
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  # booksの定義を全アクションで指定
  def book_all
    @books = Book.all
  end


end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

bookers2/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    if @model == 'user'
      @records = User.search_for(@content, @method)
    else
      @records = Book.search_for(@content, @method)
    end
  end
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @new_book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @new_book = Book.new
    @books = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name,:profile_image_id,:introduction)
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

bookers2/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers2/app/helpers/search_helper.rb
module SearchHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/df1ec9dd44.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarNavDropdown" >
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Home",user_path(current_user.id),class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "Users",users_path,class: 'fas fa-users nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "Books",books_path,class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "logout",destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Home",root_path,class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "About",home_about_path,class: 'fas fa-link nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "sign up",new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "login",new_user_session_path,class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="my-3">
      <%= render 'layouts/flash' %>
      <% if user_signed_in? %>
        <div class="search-form">
          <%= form_with url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field :content %>
            <%= f.select :model, options_for_select({"User" => "user", "Book" => "book"}) %>
            <%= f.select :method, options_for_select({"完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"}) %>
            <%= f.submit '検索' %>
          <% end %>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>