bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books,only:[:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites,only:[:create,:destroy]
    resources :post_comments,only:[:create,:destroy]
  end

  resources :users,only:[:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search', to: 'search#search'
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def self.search_for(content, method)
    if method == 'pefect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%' + content)
    else
      Book.where('title LIKE ?', '%' + content + '%')
    end
  end
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

bookers2/app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  attachment :profile_image

  validates :name,uniqueness: true,length: {in: 2..20}
  validates :introduction,length: {maximum: 50}

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  # フォロー機能ここから
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  # フォロー機能

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!,except: [:top,:about]

before_action :configure_permitted_parameters,if: :devise_controller?

def after_sign_in_path_for(resource)
  user_path(current_user)
end

protected

def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
end


end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :book_all

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
   if @new_book.save
    redirect_to book_path(@new_book[:id]), notice: 'You have created book successfully.'
   else
    @user = current_user
    render :index
   end
  end

  def index
    @new_book = Book.new
    @user = current_user
    # @books = Book.all   before_actionで定義済み
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    # @books = Book.all  before_actionで定義済み
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  # booksの定義を全アクションで指定
  def book_all
    @books = Book.all
  end


end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

bookers2/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @post_comment = current_user.post_comments.new(post_comment_params)
    # comment = PostComment.new(post_comment_params)
    # comment.user_id = current_user.id の意味
    @post_comment.book_id = @book.id
    if @post_comment.save
    redirect_to book_path(@book), notice: 'You have created comment  successfully.'
    else
    @new_book = Book.new
    @book = Book.find(params[:book_id])
    @user = @book.user
    render template: "books/show"
    end
  end

  def destroy
    PostComment.find_by(id: params[:id],book_id: params[:book_id]).destroy
    # post_comment = PostComment.find(id:params[:id], book_id: params[:book_id])
    # post_comment.destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

bookers2/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  # フォロー機能を作成・保存・削除する
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  
  
  # フォロー・フォロワー一覧を表示する
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
  
end

bookers2/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    if @model == 'user'
      @records = User.search_for(@content, @method)
    else
      @records = Book.search_for(@content, @method)
    end
  end
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @new_book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @new_book = Book.new
    @books = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name,:profile_image_id,:introduction)
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

bookers2/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers2/app/helpers/search_helper.rb
module SearchHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/_book.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag user,:profile_image,:fill,50,50,format:'jpeg',fallback:"no_image.jpg" %>
  <table class="table table-white">
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
    </tr>
  </table>
  <div class="row">
    <% if user == current_user %>
      <%= link_to "",edit_user_path(user),class:"fas fa-user-cog btn btn-outline-secondary btn-block" %>
    <% else %>
      <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete,class:"btn btn-success" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post,class:"btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model:book,local:true do |f| %>
    <div class="form-group">
      <h4>Title</h4>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <h4>Opinion</h4>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book',class:"btn btn-success" %>
    </div>
  <% end %>
</div>

bookers2/app/views/books/edit.html.erb
<% if @book.errors.any? %>
 <div id="error_explanation">
  <h4 class="text-danger"><%= @book.errors.count %>errors prohibited this obj from being saved:</h4>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
 </div>
<% end %>

<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Editing Book</h2>
    <%= form_with model:@book,local:true do |f| %>
    <div class="form-group">
      <label for= "inputTitle">Title</label><br>
      <%= f.text_field :title,autofocus: true %>
    </div>
    <div class="form-group">
      <label for= "inputBody">Opinion</label><br>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit "Update Book",class:"btn btn-success" %>
    </div>
    <% end %>
    <%= link_to "Show",book_path(@book) %>|<%= link_to "Back",books_path %>
  </div>
 </div>
</div>

bookers2/app/views/books/index.html.erb
<% if @new_book.errors.any? %>
 <div id="error_explanation">
  <h4 class="text-danger"><%= @new_book.errors.count %>errors prohibited this obj from being saved:</h4>
  <ul>
    <% @new_book.errors.full_messages.each do |message| %>
      <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
 </div>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/book',book:@new_book,user:@user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user,:profile_image, :fill,40,40, format:'jpeg', fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title,book_path(book) %></td>
              <td><%= book.body %></td>
              <td>
                <div id="favorites_buttons_<%= book.id %>"><%= render partial: 'favorites/button', locals: {book: book} %></div>
              </td>
            <td><p><%= link_to "#{book.post_comments.count}コメント",book_path(book.id) %></p></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/books/show.html.erb
<% if @post_comment.errors.any? %>
 <div id="error_explanation">
  <h4 class="text-danger"><%= @post_comment.errors.count %>errors prohibited this obj from being saved:</h4>
  <ul>
    <% @post_comment.errors.full_messages.each do |message| %>
      <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
 </div>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/book',book:@new_book,user:@user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag @book.user,:profile_image, :fill,40,40, format:"jpeg", fallback:"no_image.jpg" %><br><%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title,book_path(@book) %></td>
            <td><%= @book.body %></td>
            <% if @user.id ==  current_user.id %>
            <td><%= link_to "Edit",edit_book_path(@book),class:"btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy",book_path(@book),method: :delete,class:"btn btn-sm btn-danger" %></td>
            <% end %>
            <td>
              <div id="favorites_buttons_<%= @book.id %>"><%= render partial: 'favorites/button', locals: {book: @book} %></div>
            </td>
            <td><p>コメント件数:<%= @book.post_comments.count %></p></td>
          </tr>
        </tbody>
      </table>
      <table class="table">
        <h2><p>Comment</p></h2>
        <tbody>
          <% @book.post_comments.each do |post_comment| %>
          <tr>
            <td>
              <%= link_to user_path(post_comment.user_id) do %>
              <%= attachment_image_tag post_comment.user, :profile_image, :fill, 40, 40, format:"jpeg", fallback:"no_image.jpg" %><br><%= post_comment.user.name %>
              <% end %>
            </td>
            <td><%= post_comment.comment %></td>
            <% if post_comment.user == current_user %>
              <td><%= link_to "Destroy",book_post_comment_path(post_comment.book, post_comment),method: :delete,class:"btn btn-danger" %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <h2><p>New Comment</p></h2>
      <%= form_with(model:[@book,@post_comment],local: true) do |f| %>
        <%= f.text_area :comment, size:"60x3" %>
        <br><%= f.submit "送信",class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

bookers2/app/views/favorites/_button.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart"></i><%= book.favorites.count %>
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="far fa-heart"></i><%= book.favorites.count %>
    <% end %>
  </p>
<% end %>

bookers2/app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/button', locals: {book:@book}) %>");

bookers2/app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/button', locals: {book:@book}) %>");

bookers2/app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto mt-3">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
      </h1>
  </div>
</div>

bookers2/app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In<i class="fas fa-book"></i>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-mx-auto">
        <div class="row">
          <%= link_to "Log in",new_user_session_path,class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign Up",new_user_registration_path,class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

bookers2/app/views/relationships/followers.html.erb
<h2>Followers Users</h2>
<% if @user.exists? %>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

bookers2/app/views/relationships/followings.html.erb
<h2>Followings Users</h2>
<% if @users.exists? %>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show",user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

bookers2/app/views/search/search.html.erb
<% if @model == 'user' %>
<h3>Users search for "<%= @content %>"</h3>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @records.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% elsif @model == 'book' %>
<h3>Books search for "<%= @content %>"</h3>
<table class="table">
  <thead>
    <tr>
      <th>Titlea</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
        <%= attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg") %>
        <% end %></td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

bookers2/app/views/users/edit.html.erb
<% if @user.errors.any? %>
 <div id="error_explanation">
  <h4 class="text-danger"><%= @user.errors.count %>errors prohibited this obj from being saved:</h4>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
 </div>
<% end %>

<div class="container ">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <label for "inputName">Name</label><br>
        <%= f.text_field :name,autofocus:true %>
      </div>
        <div class="form-group">
        <%= attachment_image_tag @user,:profile_image,:fill,40,40,fallback:"no_image.jpg" %>
        <label for="inputImage">Image</label><br>
        <%= f.attachment_field :profile_image %>
      </div>
      <div class="form-group">
        <label for "inputIntroduction">Introduction</label><br>
        <%= f.text_area :introduction %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User",class:"btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

bookers2/app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/book',user:@user,book:@new_book %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user,:profile_image, :fill,40,40, format:'jpeg', fallback:"no_image.jpg" %></td>
            <td><%= user.name%></td>
            <td><%= link_to "Show",user_path(user) %></td>
            <td>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:"btn btn-success" %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-primary" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'books/book',user:@user,book:@new_book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill,40,40,format:'jpeg',fallback:"no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to book.title,book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>